# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlrActionsDemo < Formula
  desc "slr-actions-demo"
  homepage "https://github.com/ondrejsika-demo/slr-actions-demo"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.0.3/slr-actions-demo_v0.0.3_darwin_amd64.tar.gz"
      sha256 "ba948b815fcee9e9e4d7794ac838b085c3ac23b072947a35e2b5cce7cc5121cb"

      def install
        bin.install "slr-actions-demo"
      end
    end
    on_arm do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.0.3/slr-actions-demo_v0.0.3_darwin_arm64.tar.gz"
      sha256 "200cb69935c2efea91c0c8dcd9eca5fb6b22a2d54cfe12e57738368e6f3fa454"

      def install
        bin.install "slr-actions-demo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.0.3/slr-actions-demo_v0.0.3_linux_amd64.tar.gz"
        sha256 "65bfef4cd7ab67fe92c50a65649fb5e0b8eb1986cc8660928d8f7fe403f271ed"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.0.3/slr-actions-demo_v0.0.3_linux_arm64.tar.gz"
        sha256 "682a9f219a9fb92ad4c9b2041c66d6e0f0406630188c04886b516f8df6b5cf0f"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika-demo/slr-actions-demo
    EOS
  end

  test do
    system "#{bin}/slr-actions-demo version"
  end
end
