# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlrActionsDemo < Formula
  desc "slr-actions-demo"
  homepage "https://github.com/ondrejsika-demo/slr-actions-demo"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.1.0/slr-actions-demo_v0.1.0_darwin_amd64.tar.gz"
      sha256 "ca77bb6edf2f3b4e834dcfd11c2ca4078f44ff58ba7de2a28feeea9ef960954c"

      def install
        bin.install "slr-actions-demo"
      end
    end
    on_arm do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.1.0/slr-actions-demo_v0.1.0_darwin_arm64.tar.gz"
      sha256 "cc2c71c3e8903fce5b80412aec4217e945d0dda26f24bdae806af31bb0408ab8"

      def install
        bin.install "slr-actions-demo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.1.0/slr-actions-demo_v0.1.0_linux_amd64.tar.gz"
        sha256 "0e8d931e1c16fb8e843308df3b216b90c65ac6269598257df41a870551b50605"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.1.0/slr-actions-demo_v0.1.0_linux_arm64.tar.gz"
        sha256 "70170095740c8c6dd9ec26f9f30e464f462df2d8e1a6249e7adb678bf3d85c3f"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika-demo/slr-actions-demo
    EOS
  end

  test do
    system "#{bin}/slr-actions-demo version"
  end
end
