# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SlrActionsDemo < Formula
  desc "slr-actions-demo"
  homepage "https://github.com/ondrejsika-demo/slr-actions-demo"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.2.0/slr-actions-demo_v0.2.0_darwin_amd64.tar.gz"
      sha256 "17e085d1b33336f98ff702c4098f035d0a07151dd9565ea047e5f932c15245b2"

      def install
        bin.install "slr-actions-demo"
      end
    end
    on_arm do
      url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.2.0/slr-actions-demo_v0.2.0_darwin_arm64.tar.gz"
      sha256 "a061826ce45ca973e18f75cce533f94861586fba71601fb6a4efcd603ea9e90f"

      def install
        bin.install "slr-actions-demo"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.2.0/slr-actions-demo_v0.2.0_linux_amd64.tar.gz"
        sha256 "89f78b6f0433c309777a59caa0894cd0a7f81c2df6251bcb5a8cb0a133f3abd6"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ondrejsika-demo/slr-actions-demo/releases/download/v0.2.0/slr-actions-demo_v0.2.0_linux_arm64.tar.gz"
        sha256 "6701d215d1da98ce243488e4534d834c13b825f5025cce404e5302365648e224"

        def install
          bin.install "slr-actions-demo"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika-demo/slr-actions-demo
    EOS
  end

  test do
    system "#{bin}/slr-actions-demo version"
  end
end
